# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'BuddyUpApp' do
pod 'Firebase'
pod 'Firebase/Auth'
pod 'JTAppleCalendar', '~> 7.0'

end
